name: HandTracker

on:
  push:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v2
    - uses: actions/checkout@master
      
    - name: Install Conan
      run: pip install conan

    - name: Create Build Environment
      run: sudo apt-get update --fix-missing && sudo apt-get install libxcb-image0-dev && sudo apt-get install libxcb-icccm4-dev && sudo apt-get install libgl1-mesa-dev && sudo apt-get install libxcb-xkb-dev && sudo apt-get install libglu1-mesa-dev && sudo apt-get install xorg-dev && sudo apt-get install libxcb-render-util0-dev && sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update -qq && sudo apt-get install -qq g++-9 && sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 90 && cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE
